name: CI Worker (Golang)
on: [push, pull_request]
jobs:
  build:
    name: CI Worker (Golang)
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.5
        id: go

      - name: Check out source
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install libgit2
        run: sudo ./scripts/install_libgit2.sh

      - name: Vet
        run: make vet

      - name: Test
        run: make test

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.47.3
          make lint-ci
